#ifndef C7_BRICKGAME_V1_0_1_SRC_BRICK_GAME_TETRIS_BACKEND_CELL_CELL_H_
#define C7_BRICKGAME_V1_0_1_SRC_BRICK_GAME_TETRIS_BACKEND_CELL_CELL_H_

#include "structs.h"

void SetCell(Cell *p_cell);
Cell GetCell(Cell *p_cell);

#endif //C7_BRICKGAME_V1_0_1_SRC_BRICK_GAME_TETRIS_BACKEND_CELL_CELL_H_
